<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * AutorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AutorRepository extends \Doctrine\ORM\EntityRepository
{
	public function findAll()
    {
        return $this->findBy(array(), array('ime' => 'ASC'));
    }
}
