<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * KomentarRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class KomentarRepository extends \Doctrine\ORM\EntityRepository
{
	public function findAll()
    {
        return $this->findBy(array(), array('vrijeme' => 'desc'));
    }
}
